version: "3.12.4"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=personalBudgetApp
      - POSTGRES_USER=personalBudgetApp
      - POSTGRES_PASSWORD=personalBudgetApp
    volumes:
      #- .:/code
      - personalBudgetApp-volume:/var/lib/postgresql/data
    # - ./onlineshop-volume:/var/lib/postgresql/data
volumes:
  personalBudgetApp-volume:
